=== hmcts/pdda-shared-infrastructure/src/main/resources/config/xml/PublicNotice.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 3 U (http://www.xmlspy.com) by Alex Brown (Electronic Data Systems LTD) -->
<!--W3C Schema generated by XMLSPY v5 rel. 3 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="PublicNotice">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="CourtLogEvent" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="DefinitivePublicNotice" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="defPNId" type="xs:string" use="required"/>
											<xs:attribute name="status" type="xs:string" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="Type" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== hmcts/pdda-shared-infrastructure/src/main/resources/config/xml/PublicNotice.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSPY v5 rel. 3 U (http://www.xmlspy.com)-->
<PublicNotice xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="config\xml\PublicNotice.xsd">

  <!-- Reporting Restrictions log events trigger the REPORTING RESTRICTIONS. FOR DETAILS PLEASE SEE COURT MANAGER public notice -->
  <CourtLogEvent Type="21200">
    <DefinitivePublicNotice defPNId="100" status="true"/>
    <DefinitivePublicNotice defPNId="700" status="false"/>
  </CourtLogEvent>

  <!-- Reporting Restrictions Lifted log events trigger the REPORTING RESTRICTIONS LIFTED public notice -->
  <CourtLogEvent Type="21201">
    <DefinitivePublicNotice defPNId="700" status="true"/>
    <DefinitivePublicNotice defPNId="100" status="false"/>
  </CourtLogEvent>

  <!-- Summing Up log events trigger the IF YOU WISH TO ENTER, PLEASE DO SO QUIETLY public notice -->
  <CourtLogEvent Type="20911">
    <DefinitivePublicNotice defPNId="600" status="true"/>
  </CourtLogEvent>

  <!--  Prosecution Case - TV Link in Progress or log events trigger the TV BEING PLAYED - PLEASE ENTER QUIETLY public notice -->
  <CourtLogEvent Type="2090301">
    <DefinitivePublicNotice defPNId="400" status="true"/>
  </CourtLogEvent>

  <!--  Prosecution Case - Video Link in Progress or log events trigger the VIDEO BEING PLAYED - PLEASE ENTER QUIETLY public notice -->
  <CourtLogEvent Type="2090302">
    <DefinitivePublicNotice defPNId="500" status="true"/>
  </CourtLogEvent>

  <!--  Respondent Case - TV Link in Progress or log events trigger the VIDEO BEING PLAYED - PLEASE ENTER QUIETLY public notice -->
  <CourtLogEvent Type="2060201">
    <DefinitivePublicNotice defPNId="400" status="true"/>
  </CourtLogEvent>

  <!--  Respondent Case - Video Link in Progress or log events trigger the VIDEO BEING PLAYED - PLEASE ENTER QUIETLY public notice -->
  <CourtLogEvent Type="2060202">
    <DefinitivePublicNotice defPNId="500" status="true"/>
  </CourtLogEvent>

</PublicNotice>
